### ISSUE TITLE
Post links can throw 500 internal server errors

### ISSUE THREAD

**Issue by Nothing4You** [RikudouSage/lemmyverse.link#1]
example: https://lemmyverse.link/lemmy.today/post/4312610

this doesn't seem to be consistent for all users.
when this link was shared, some users had no issues, while other users received an internal server error:

![image](https://github.com/RikudouSage/lemmyverse.link/assets/3694534/dacad082-c839-416c-a5db-d70af699c101)

**Comment by RikudouSage** [comment]
Unless there's another problem, it should be fixed by #2. Feel free to reopen if you encounter the same issue again.

**Comment by Nothing4You** [comment]
Still broken unfortunately, both with the original link and this one: https://lemmyverse.link/lemmy.world/comment/6221447

I can reproduce this with various instances as home instance, for example:
- sopuli.xyz - exists at https://sopuli.xyz/comment/5590397
- lemm.ee - exists at https://lemm.ee/comment/7558501

working instances:
- lemmy.world
- lemmy.ml
- feddit.de
- lemmy.ca

**Comment by RikudouSage** [comment]
This seems to be because the comment is deleted on lemmy.world.

**Comment by Nothing4You** [comment]
here you go: https://lemmyverse.link/lemmy.world/comment/8760207

**Comment by RikudouSage** [comment]
Fixed, thanks for the report!
